image: php:7.1-fpm-alpine

variables:
  CPANEL_USERNAME: univsec
  CPANEL_SERVER: secretary.unm.edu
  TEST_DIRECTORY: freshmanconvocation-test.unm.edu
  PROD_DIRECTORY: freshmanconvocation.unm.edu
  PUBLIC_HTML: /home/univsec/public_html

stages:
  - deploy

before_script:
  - apk update
  - apk add --no-cache openssh sshpass composer git php7-curl
  - composer install --no-dev --prefer-dist --ignore-platform-reqs --optimize-autoloader

deploy_test:
  stage: deploy
  environment:
    name: test
    url: https://freshmanconvocation-test.unm.edu
  script: |
    echo "setting up deploying message and clearing old files"
    sshpass -p $UNIVSEC_CPANEL_P ssh -o StrictHostKeyChecking=no -c aes256-cbc ${CPANEL_USERNAME}@${CPANEL_SERVER} /bin/sh << EOF
      cd ${PUBLIC_HTML}/${TEST_DIRECTORY}
      cp ${PUBLIC_HTML}/deploying.php web/index.php
      cp ${PUBLIC_HTML}/deploying.htaccess web/.htaccess
      rm -rf digraph/*
      rm -rf media/*
      rm -rf modules/*
      rm -rf routes/*
      rm -rf templates/*
      rm -rf digraph/*
    EOF
    echo "deploying digraph"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      digraph \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${TEST_DIRECTORY}
    echo "deploying media"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      media \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${TEST_DIRECTORY}
    echo "deploying modules"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      modules \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${TEST_DIRECTORY}
    echo "deploying routes"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      routes \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${TEST_DIRECTORY}
    echo "deploying templates"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      templates \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${TEST_DIRECTORY}
    echo "deploying digraph.yaml"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      digraph.yaml \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${TEST_DIRECTORY}/digraph.yaml
    echo "deploying web"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      web \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${TEST_DIRECTORY}

deploy_prod:
  stage: deploy
  when: manual
  only:
    - master
  environment:
    name: production
    url: https://freshmanconvocation.unm.edu
  script: |
    echo "setting up deploying message and clearing old files"
    sshpass -p $UNIVSEC_CPANEL_P ssh -o StrictHostKeyChecking=no -c aes256-cbc ${CPANEL_USERNAME}@${CPANEL_SERVER} /bin/sh << EOF
      cd ${PUBLIC_HTML}/${PROD_DIRECTORY}
      cp ${PUBLIC_HTML}/deploying.php web/index.php
      cp ${PUBLIC_HTML}/deploying.htaccess web/.htaccess
      rm -rf digraph/*
      rm -rf media/*
      rm -rf modules/*
      rm -rf routes/*
      rm -rf templates/*
      rm -rf digraph/*
    EOF
    echo "deploying digraph"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      digraph \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${PROD_DIRECTORY}
    echo "deploying media"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      media \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${PROD_DIRECTORY}
    echo "deploying modules"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      modules \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${PROD_DIRECTORY}
    echo "deploying routes"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      routes \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${PROD_DIRECTORY}
    echo "deploying templates"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      templates \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${PROD_DIRECTORY}
    echo "deploying digraph.yaml"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      digraph.yaml \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${PROD_DIRECTORY}/digraph.yaml
    echo "deploying web"
    sshpass -p $UNIVSEC_CPANEL_P scp -r -o StrictHostKeyChecking=no -c aes256-cbc \
      web \
      ${CPANEL_USERNAME}@${CPANEL_SERVER}:${PUBLIC_HTML}/${PROD_DIRECTORY}
